apiVersion: v1
kind: Service
metadata:
  name: whatsapp-webhook-service
  labels:
    app: whatsapp-webhook
spec:
  selector:
    app: whatsapp-webhook
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP