apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-webhook-secrets
type: Opaque
stringData:
  WEBHOOK_VERIFY_TOKEN: "visionary"
  API_TOKEN: "EAANFoMoGXJEBOw06of8ekwSZAod10G1bZB7FgNv4T0y8ZBM50ZBG9QCFQt831gtwxw6kBPToO6dltGsAKQezOxek4ji2vGA0ykavMswmYPXgByWqo5lSrAZBvwerBQzWNpZBJhPDc1Y8r0ZBlp3RlZCm8oHZBCIcx6ZCOtSbCXmI49fdGZAaeWLkgkeoJShT7t5nUfmIMy0Jf3BNhaZAWCezrsXcuNCRtlMscCo1KOYZD"